#!/bin/bash

set -e

restore_configs

export V1_VERSION=${V1_VERSION}D

$CFGDIR/common/v1-base-config
$CFGDIR/common/cnc-config
$CFGDIR/boards/skr_turbo_1p4
$CFGDIR/accessories/dummy-extruder
$CFGDIR/accessories/tmc2209
# $CFGDIR/accessories/reprap_discount_full_graphic_lcd
$CFGDIR/accessories/mks12864-mini-v3
$CFGDIR/accessories/dual-drivers-on-xy
$CFGDIR/boards/skr_turbo_1p4_dual

opt_set X2_DRIVER_TYPE "TMC2209"
opt_set Y2_DRIVER_TYPE "TMC2209"

opt_set X_BED_SIZE "450"
opt_set Y_BED_SIZE "590"

export PLATFORMIO_ENV=LPC1769
